In [1]:
#1. NumPy kütüphanesi np kısaltması ile import edin

In [2]:
import numpy as np

In [3]:
#2. 10 tane 0 değerinden oluşan bir array oluşturun

In [5]:
arrd=np.zeros(10)
arrd

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#3. 10 tane 1 değerinden oluşan bir array oluşturun

In [8]:
asd=np.ones(10)
asd

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
#4. 10 tane 5 değerinden oluşan bir array oluşturun

In [12]:
asz=np.ones(10)*5
asz

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
#5. 10'dan 50'ye kadar(10 ve 50 dahil) ardışık tam sayılardan oluşan bir array oluşturalım

In [15]:
axs=np.arange(10,51)
axs

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
#6. 10 ve 50 arasındaki çift tam sayılardan oluşan bir array oluşturalım. (10 ve 50 dahil)

In [18]:
snx=np.arange(10,51,2)
snx

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
#7. 3x3 shape'inde 0'dan 8'e kadar toplam 9 tam sayıdan oluşan bir array oluşturalım

In [22]:
sds=np.arange(0,9).reshape(3,3)
sds

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
#8. 3x3 boyutlarında birim matris oluşturun

In [33]:
xsa=np.eye(3)
xsa

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#9. NumPy kullanarak 0-1 arasından rastgele bir sayı oluşturun.

In [3]:
lsa=np.random.rand(1)
lsa

array([0.18140126])

In [42]:
#10. NumPy kullanarak standart dağılıma sahip 25 random sayıdan oluşan bir array oluşturalım.


In [5]:
uds=np.random.randn(10,500,25)
uds

array([[[-3.34213960e-02,  1.09513121e-01,  1.02612919e+00, ...,
         -4.77887803e-01,  1.08357533e+00, -1.00108157e+00],
        [-1.50358797e+00,  1.41832184e+00,  2.29667263e+00, ...,
          7.86895417e-01, -8.17502190e-01, -1.38163394e-01],
        [-7.14384873e-01, -5.33489311e-01, -6.18365841e-01, ...,
          6.21639319e-01,  1.05357590e+00, -5.55147833e-01],
        ...,
        [ 7.58377126e-02, -1.05591437e+00, -7.25617132e-01, ...,
          8.84144094e-01, -3.78469814e-01,  4.23985629e-01],
        [ 1.71501048e+00, -4.27205278e-01, -1.39120040e+00, ...,
         -4.12343721e-01,  1.83308755e+00,  2.18069900e+00],
        [ 3.14652329e-01,  1.77179517e+00, -7.30984575e-02, ...,
         -2.15579613e-01,  4.22934561e-01, -8.78614859e-01]],

       [[-9.26157419e-01,  4.75017874e-01, -5.18729120e-01, ...,
         -1.11354921e+00, -2.90764009e+00, -1.21234389e+00],
        [ 6.85032764e-01,  3.55844483e-01,  2.78578352e-02, ...,
          7.91279159e-01,  5.74366174e

In [45]:
#11. Aşağıdaki çıktıdakine benzer array'i oluşturmaya çalışın

In [21]:
gsd=np.linspace(0.0,1,100,dtype='float').reshape(10,10).round(2)
gsd

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [68]:
#12. 0-1 arasında lineer artış gösteren ve 20 sayıdan oluşan bir array oluşturun:

In [70]:
dsd=np.linspace(0,1,20)
dsd

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [25]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
#13. Aşağıda verilen matrisleri oluşturmaya çalışın.

In [26]:
mat[2:5,1:5]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [98]:
#14. Aşağıda gösterilen çıktıyı üreten kodu yazın.

In [99]:
mat[3,4]

20

In [100]:
#15. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [28]:
mat[0:3,:1]

array([[ 1],
       [ 6],
       [11]])

In [107]:
#16. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [113]:
mat[4,0:5]

array([21, 22, 23, 24, 25])

In [114]:
#17. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [118]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#18. Mat arrayindeki bütün değerlerin toplamını bulun

In [119]:
mat.sum()

325

In [120]:
#19. Mat arrayindeki değerlerin standart sapmasını bulun

In [121]:
mat.std()

7.211102550927978

In [122]:
#20. Mat arrayindeki her sütunun kendi içinde toplamlarını bularak yeni bir array oluşturun

In [123]:
mat.sum(0)

array([55, 60, 65, 70, 75])