In [88]:
import numpy as np

In [1]:
#1-Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın.Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

In [8]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3d.ndim


3

In [9]:
#2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.


In [12]:
arr=np.arange(34,113,6)
arr

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [13]:
#3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

In [16]:
arr91= np.linspace(50,500,91, dtype=int)
arr91

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [17]:
#4)100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [19]:
arrd=np.logspace(2,5,8)
arrd

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [20]:
#5)0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [29]:
arr3d= np.arange(0,9).reshape(3,3)
arr3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
#6)6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [160]:
np.zeros((6,6), dtype='int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [33]:
#7)4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

In [162]:
arr4d= np.ones((4,4), dtype='int')
arr4d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
#8)8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [49]:
arr8d=np.eye(8,dtype='int')
arr8d

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [50]:
#9)5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

In [92]:
np.diag([3,3,3,3,3])


array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [93]:
#10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [97]:
arr=np.random.rand(6)
arr

array([0.89497121, 0.01897176, 0.66064196, 0.18681412, 0.26599561,
       0.81318214])

In [98]:
#11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [164]:
arrd=np.random.randint(50,101,10).reshape(5,2)
arrd

array([[77, 72],
       [85, 85],
       [59, 91],
       [50, 97],
       [58, 75]])

In [165]:
arrd.shape

(5, 2)

In [ ]:
#12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [130]:
arrdx=np.random.randint(100,1000,50).reshape(2,5,5)
arrdx


array([[[996, 814, 541, 676, 239],
        [541, 150, 693, 816, 366],
        [200, 163, 422, 737, 742],
        [447, 669, 937, 504, 765],
        [938, 227, 136, 993, 507]],

       [[907, 610, 436, 504, 282],
        [593, 936, 425, 490, 652],
        [205, 892, 424, 304, 166],
        [880, 967, 752, 652, 303],
        [187, 462, 183, 135, 586]]])

In [131]:
arrdx.ndim

3

In [132]:
arrdx.shape

(2, 5, 5)

In [133]:
#13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [166]:
arrdy=np.random.randint(0,101,10)
arrdy

array([55, 94, 39, 34, 78, 75, 85, 46, 45, 19])

In [167]:
arrdy.max()

94

In [168]:
arrdy.argmax()

1

In [169]:
arrdy.min()

19

In [170]:
arrdy.argmin()

9

In [ ]:
#14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [176]:
ard=np.random.randint(300,501,20).reshape(2,2,5)
ard

array([[[386, 493, 437, 468, 327],
        [351, 417, 457, 375, 454]],

       [[448, 442, 341, 350, 486],
        [364, 471, 436, 308, 332]]])

In [180]:
ard[0,0,1]

493

In [181]:
ard[1,1,3]

308

In [ ]:
#15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [183]:
arx=np.arange(0,51,1)
arx[20:35]=500

arx

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])